import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { Bell, ChevronRight, CircleUserRound, CreditCard, Download, Globe2, Shield, Smartphone, Trash2, KeyRound } from 'lucide-react';

type Item={title:string;description:string;icon:typeof Bell;href?:string;danger?:boolean;disabled?:boolean};
const account:Item[]=[{title:'Profile',description:'Name, email, avatar',icon:CircleUserRound,href:'/profile'},{title:'Billing & Plan',description:'Subscription and plan details',icon:CreditCard,href:'/upgrade'},{title:'Notifications',description:'Reminders and alerts',icon:Bell,href:'/notifications'}];
const app:Item[]=[{title:'Language & Region',description:'Language and preferred currency',icon:Globe2,href:'/settings/preferences'},{title:'Install as app',description:'Add Mirqo from your browser menu',icon:Smartphone,disabled:true}];
const security:Item[]=[{title:'Two-factor authentication',description:'Not enabled',icon:Shield,disabled:true}];
const data:Item[]=[{title:'Export data',description:'Secure export is not enabled yet',icon:Download,disabled:true},{title:'Delete account',description:'Requires a separately confirmed secure workflow',icon:Trash2,danger:true,disabled:true}];
export default async function Page(){const supabase=await createClient();const{data:isAdmin}=await supabase.rpc('is_activation_admin');return <div className="mx-auto max-w-2xl"><h1 className="text-xl font-bold tracking-tight sm:text-2xl">Settings</h1><div className="mt-8 space-y-6"><Section label="Account" items={account}/><Section label="App" items={app}/><Section label="Security" items={security}/>{isAdmin&&<Section label="Admin" items={[{title:'Activation codes',description:'Create and revoke Pro access codes',icon:KeyRound,href:'/admin/activation-codes'}]}/>}<Section label="Data" items={data}/></div><p className="mt-8 text-center text-xs text-slate-400">Mirqo v0.1.0 · Built with <span className="text-red-500">♥</span></p></div>}
function Section({label,items}:{label:string;items:Item[]}){return <section><h2 className="mb-3 text-[11px] font-bold uppercase tracking-[.15em] text-slate-500">{label}</h2><div className="divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{items.map(item=><Row key={item.title} item={item}/>)}</div></section>}
function Row({item}:{item:Item}){const Icon=item.icon;const content=<><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${item.danger?'bg-red-50 text-red-500':'bg-slate-100 text-slate-500'}`}><Icon size={16}/></span><span className="min-w-0 flex-1"><span className={`block text-sm font-semibold ${item.danger?'text-red-500':'text-slate-900'}`}>{item.title}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{item.description}</span></span><ChevronRight size={16} className="shrink-0 text-slate-400"/></>;const classes=`flex w-full items-center gap-4 px-5 py-4 text-left transition ${item.disabled?'cursor-not-allowed opacity-70':'hover:bg-slate-50'}`;return item.href?<Link href={item.href} className={classes}>{content}</Link>:<div aria-disabled={item.disabled} title={item.disabled?'This feature is not enabled yet':undefined} className={classes}>{content}</div>}