import { createClient } from '@/lib/supabase/server';import type { Subscription } from '@/types/database';
const scope='https://www.googleapis.com/auth/calendar.events';
function config(){const clientId=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,secret=process.env.GOOGLE_CLIENT_SECRET,base=process.env.NEXT_PUBLIC_APP_URL,key=process.env.GOOGLE_TOKEN_ENCRYPTION_KEY;if(!clientId||!secret||!base||!key)throw new Error('Google Calendar is not configured.');return{clientId,secret,base,key}}
export async function stateFor(userId:string,subscriptionId:string){const payload=toUrl(JSON.stringify({userId,subscriptionId,expires:Date.now()+600000}));return payload+'.'+await sign(payload)}
export async function readState(value:string){const[payload,signature]=value.split('.');if(!payload||!signature||signature!==await sign(payload))throw new Error('Invalid OAuth state.');const data=JSON.parse(fromUrl(payload)) as {userId:string;subscriptionId:string;expires:number};if(data.expires<Date.now())throw new Error('OAuth state expired.');return data}
async function sign(value:string){const{key}=config();const cryptoKey=await crypto.subtle.importKey('raw',Buffer.from(key,'base64'),{name:'HMAC',hash:'SHA-256'},false,['sign']);return toUrl(Buffer.from(await crypto.subtle.sign('HMAC',cryptoKey,Buffer.from(value))))}
export function authorizationUrl(state:string){const{clientId,base}=config();return'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:clientId,redirect_uri:base+'/api/calendar/callback',response_type:'code',scope,access_type:'offline',prompt:'consent',include_granted_scopes:'true',state}).toString()}
export async function exchange(code:string){const{clientId,secret,base}=config();const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:secret,code,grant_type:'authorization_code',redirect_uri:base+'/api/calendar/callback'})});if(!response.ok)throw new Error('Google token exchange failed.');return response.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number;scope?:string}>}
export async function encrypt(value:string){const{key}=config();const iv=crypto.getRandomValues(new Uint8Array(12));const k=await crypto.subtle.importKey('raw',Buffer.from(key,'base64'),'AES-GCM',false,['encrypt']);const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,Buffer.from(value));return Buffer.concat([Buffer.from(iv),Buffer.from(data)]).toString('base64')}
export async function decrypt(value:string){const{key}=config();const raw=Buffer.from(value,'base64'),iv=raw.subarray(0,12);const k=await crypto.subtle.importKey('raw',Buffer.from(key,'base64'),'AES-GCM',false,['decrypt']);return Buffer.from(await crypto.subtle.decrypt({name:'AES-GCM',iv},k,raw.subarray(12))).toString()}
function eventBody(s:Subscription){const end=new Date(s.renewal_date+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+1);const event:{summary:string;description:string;start:{date:string};end:{date:string};recurrence?:string[];reminders:{useDefault:boolean;overrides:{method:string;minutes:number}[]}}={summary:s.service_name+' renewal',description:'Mirqo subscription renewal: '+s.currency+' '+s.amount,start:{date:s.renewal_date},end:{date:end.toISOString().slice(0,10)},reminders:{useDefault:false,overrides:[{method:'popup',minutes:s.reminder_days_before*1440}]}};if(s.billing_cycle!=='trial')event.recurrence=['RRULE:FREQ='+(s.billing_cycle==='yearly'?'YEARLY':'MONTHLY')];return event}
export async function createEvent(accessToken:string,s:Subscription){const response=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify(eventBody(s))});if(!response.ok)throw new Error('Google event creation failed.');return response.json() as Promise<{id:string}>}
export async function updateEvent(accessToken:string,eventId:string,s:Subscription){const response=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events/'+encodeURIComponent(eventId),{method:'PUT',headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json'},body:JSON.stringify(eventBody(s))});if(!response.ok)throw new Error('Google event update failed.')}
export async function deleteEvent(accessToken:string,eventId:string){const response=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events/'+encodeURIComponent(eventId),{method:'DELETE',headers:{Authorization:'Bearer '+accessToken}});if(!response.ok&&response.status!==404&&response.status!==410)throw new Error('Google event deletion failed.')}
export async function calendarAccessToken(userId:string){const supabase=await createClient();const{data}=await supabase.from('google_calendar_connections').select('access_token_encrypted,refresh_token_encrypted,expires_at').eq('user_id',userId).maybeSingle();if(!data)return null;if(new Date(data.expires_at).getTime()>Date.now()+60000)return decrypt(data.access_token_encrypted);if(!data.refresh_token_encrypted)return null;const{clientId,secret}=config();const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:secret,refresh_token:await decrypt(data.refresh_token_encrypted),grant_type:'refresh_token'})});if(!response.ok)return null;const tokens=await response.json() as {access_token:string;expires_in:number};await supabase.from('google_calendar_connections').update({access_token_encrypted:await encrypt(tokens.access_token),expires_at:new Date(Date.now()+tokens.expires_in*1000).toISOString(),updated_at:new Date().toISOString()}).eq('user_id',userId);return tokens.access_token}
function toUrl(value:string|Buffer){return Buffer.from(value).toString('base64url')}function fromUrl(value:string){return Buffer.from(value,'base64url').toString()}
export async function ownedSubscription(id:string){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data}=await supabase.from('subscriptions').select('*').eq('id',id).eq('user_id',user.id).maybeSingle();return data?{user,subscription:data as Subscription,supabase}:null}
