"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Bell, CalendarDays, Check, ChevronDown, Eye, Menu, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { logLandingEvent } from "@/features/analytics/actions/landing-events";

const track = (event: string) => { void logLandingEvent(event); };

export function LandingPage() {
  const [open, setOpen] = useState(false);
  useEffect(() => { track("landing_view"); }, []);
  const close = () => setOpen(false);
  return <main className="landing-blue min-h-screen overflow-hidden bg-[#f5f8ff] text-[#0b1f3a]">
    <nav className="relative z-20 mx-auto flex h-[76px] max-w-6xl items-center justify-between px-5 sm:px-8"><Logo href="/"/><div className="hidden items-center gap-8 text-xs font-bold text-[#54717a] md:flex"><a href="#features" className="hover:text-[#082f3d]">Features</a><a href="#how" className="hover:text-[#082f3d]">How it works</a><a href="#faq" className="hover:text-[#082f3d]">FAQ</a></div><div className="hidden items-center gap-2 md:flex"><Link href="/login" onClick={() => track("sign_in_clicked")} className="rounded-lg px-4 py-2 text-xs font-bold text-[#54717a] hover:bg-white">Sign in</Link><Link href="/signup" onClick={() => track("navbar_start_free_clicked")} className="rounded-lg bg-[#2d96a4] px-5 py-2.5 text-xs font-bold text-white shadow-lg shadow-[#2d96a4]/20 hover:bg-[#237d89]">Start free ↗</Link></div><button type="button" aria-label="Open menu" onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center rounded-lg border border-[#d7e6e8] bg-white md:hidden">{open ? <X size={18}/> : <Menu size={18}/>}</button></nav>
    {open && <div className="relative z-30 border-y border-[#dbe9eb] bg-white px-5 py-4 md:hidden"><div className="grid gap-1 text-sm font-bold text-[#54717a]"><a href="#features" onClick={close} className="px-3 py-2">Features</a><a href="#how" onClick={close} className="px-3 py-2">How it works</a><a href="#faq" onClick={close} className="px-3 py-2">FAQ</a><Link href="/login" onClick={() => { track("sign_in_clicked"); close(); }} className="mt-2 rounded-lg bg-[#f1f7f8] px-3 py-3">Sign in</Link><Link href="/signup" onClick={() => { track("navbar_start_free_clicked"); close(); }} className="rounded-lg bg-[#2d96a4] px-3 py-3 text-center text-white">Start free</Link></div></div>}

    <section className="relative mx-auto max-w-6xl px-5 pb-28 pt-14 sm:px-8 sm:pt-20 lg:px-10 lg:pt-24"><div className="pointer-events-none absolute -right-20 top-0 h-[520px] w-[520px] rounded-full bg-[#cbe9eb]/70 blur-3xl"/><div className="relative grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-12"><div><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-[#2d96a4]"><Sparkles size={13}/> Public beta · Pro unlocked</span><h1 className="mt-6 max-w-xl text-5xl font-black leading-[1.02] tracking-[-.065em] text-[#073442] sm:text-6xl lg:text-[72px]">Know before<br/>you&apos;re charged.</h1><p className="mt-6 max-w-md text-base leading-7 text-[#64818a] sm:text-lg">Track subscriptions, renewals and recurring payments in one clear place—so you always know what&apos;s coming next.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" onClick={() => track("hero_start_free_clicked")} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[#2d96a4] px-6 text-sm font-bold text-white shadow-xl shadow-[#2d96a4]/20 hover:bg-[#237d89]">Start free <ArrowRight size={16}/></Link><a href="#how" onClick={() => track("hero_see_how_it_works_clicked")} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-[#cfe2e4] bg-white/70 px-6 text-sm font-bold text-[#315b65] hover:bg-white">See how it works <Eye size={16}/></a></div><p className="mt-4 text-[11px] font-semibold text-[#8aa1a7]">Free during beta · No credit card required</p></div><HeroPreview/></div></section>

    <section id="features" className="relative z-10 mx-auto -mb-2 max-w-5xl px-5 sm:px-8"><div className="rounded-2xl border border-[#e2ecee] bg-white p-7 shadow-[0_18px_50px_rgba(8,47,61,.08)] sm:p-10"><div className="grid gap-8 lg:grid-cols-[.9fr_1.6fr]"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#2d96a4]">Your money, in focus</p><h2 className="mt-3 text-3xl font-black leading-tight tracking-[-.04em]">A clearer view of recurring payments.</h2><p className="mt-3 text-sm leading-6 text-[#708b92]">Everything you need to know before the next charge, without the noise.</p></div><div className="grid gap-7 sm:grid-cols-3"><Feature icon={CalendarDays} title="Upcoming renewals" text="See what is renewing next."/><Feature icon={WalletCards} title="Recurring spend" text="Understand monthly and yearly cost."/><Feature icon={ShieldCheck} title="Private by design" text="Your records stay yours."/></div></div></div></section>

    <section className="mx-auto max-w-6xl px-5 pb-24 pt-28 sm:px-8 lg:px-10"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#2d96a4]">Why MYRQO</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-4xl">Clarity that grows with your life.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-[#e2ecee]"><p className="text-6xl font-black tracking-[-.08em] text-[#2d96a4]">1</p><h3 className="mt-5 text-lg font-black">One place for every renewal</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#708b92]">Subscriptions, bills, memberships and installments—organized in one calm overview.</p></div><div className="rounded-2xl bg-[#eaf5f6] p-7"><div className="flex items-center justify-between"><h3 className="text-lg font-black">Your next payment, visible</h3><Bell size={19} className="text-[#2d96a4]"/></div><div className="mt-8 rounded-xl bg-white p-4 shadow-sm"><Renewal name="iCloud+" date="in 2 days" amount="$2.99" color="bg-[#398fdb]"/><Renewal name="Netflix" date="in 4 days" amount="$15.49" color="bg-[#e5484d]"/><Renewal name="Spotify" date="in 8 days" amount="$11.99" color="bg-[#21b66f]"/></div></div></div></section>

    <section id="how" className="bg-[#073c4d] px-5 py-20 text-white sm:px-8 lg:py-24"><div className="mx-auto max-w-6xl"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#79cbd0]">Simple by design</p><h2 className="mt-4 max-w-xl text-3xl font-black tracking-[-.04em] sm:text-4xl">Stay ahead of the next charge.</h2><div className="mt-12 grid gap-4 md:grid-cols-3"><Step number="1" title="Add your subscription" text="Name, price, renewal date and frequency."/><Step number="2" title="See what’s coming" text="MYRQO organizes renewals and recurring spend."/><Step number="3" title="Stay ahead" text="Know what is renewing before it arrives."/></div></div></section>

    <section className="mx-auto max-w-6xl px-5 py-24 sm:px-8 lg:px-10"><div className="grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#2d96a4]">Control, not clutter</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">See what&apos;s coming next.</h2><p className="mt-5 text-base leading-7 text-[#708b92]">Your renewals should never be a surprise. Upcoming charges, dates and recurring expenses stay where you can see them.</p><Link href="/signup" onClick={() => track("final_cta_clicked")} className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#2d96a4] px-5 text-sm font-bold text-white hover:bg-[#237d89]">Start tracking <ArrowRight size={16}/></Link></div><div className="rounded-2xl border border-[#e1ecee] bg-white p-6 shadow-[0_14px_38px_rgba(8,47,61,.07)]"><div className="flex items-center justify-between"><p className="text-sm font-black">Upcoming renewals</p><span className="rounded-full bg-[#e8f6f1] px-3 py-1 text-[10px] font-bold text-[#209260]">This week</span></div><Renewal name="iCloud+" date="Renews Jul 22 · in 2 days" amount="$2.99" color="bg-[#398fdb]"/><Renewal name="Netflix" date="Renews Jul 24 · in 4 days" amount="$15.49" color="bg-[#e5484d]"/><Renewal name="Spotify" date="Renews Jul 28 · in 8 days" amount="$11.99" color="bg-[#21b66f]"/></div></div></section>

    <section className="bg-[#2d96a4] px-5 py-20 text-white sm:px-8 lg:py-24"><div className="mx-auto max-w-3xl text-center"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#c3f0f1]">Public beta</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">Everything unlocked during beta.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[#d8f3f4]">Every account gets access to all current Pro features for free while we build MYRQO with early users.</p><div className="mx-auto mt-8 grid max-w-lg gap-3 text-left sm:grid-cols-2">{["All current Pro features","No credit card required","Send feedback inside MYRQO","Early access to improvements"].map(item => <p key={item} className="flex items-center gap-2 text-sm font-bold"><Check size={16} className="text-[#c3f0f1]"/>{item}</p>)}</div><Link href="/signup" onClick={() => track("beta_join_clicked")} className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-lg bg-white px-6 text-sm font-bold text-[#1f7884] hover:bg-[#effcfc]">Join the beta <ArrowRight size={16}/></Link></div></section>

    <section id="faq" className="mx-auto max-w-3xl px-5 py-24 sm:px-8"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#2d96a4]">FAQ</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em]">Questions, answered.</h2></div><div className="mt-10 divide-y divide-[#e1ecee] rounded-2xl border border-[#e1ecee] bg-white px-6">{[["What is MYRQO?","MYRQO helps you track subscriptions, recurring payments and renewal dates."],["Is MYRQO free?","During the public beta, all current Pro features are unlocked for free."],["Can I install it on my phone?","Yes. MYRQO is a Progressive Web App and can be added to your home screen."],["Does MYRQO connect to my bank?","Not during the current beta. You manage subscriptions directly inside MYRQO."],["Is my data private?","Authenticated users can access only their own private records through row-level security."]].map(([q,a]) => <details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-bold">{q}<ChevronDown size={16} className="transition group-open:rotate-180"/></summary><p className="mt-3 text-sm leading-6 text-[#708b92]">{a}</p></details>)}</div></section>

    <section className="px-5 pb-20 sm:px-8"><div className="mx-auto max-w-5xl rounded-2xl bg-[#073c4d] px-6 py-14 text-center text-white sm:px-12"><h2 className="text-3xl font-black tracking-[-.04em] sm:text-4xl">Take control of your next renewal.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-[#a9c5ca]">Start tracking your subscriptions today and know what&apos;s coming before you&apos;re charged.</p><Link href="/signup" onClick={() => track("final_cta_clicked")} className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#2d96a4] px-6 text-sm font-bold hover:bg-[#43adba]">Start free <ArrowRight size={16}/></Link><p className="mt-4 text-xs text-[#8eafb5]">Free during public beta · No credit card required</p></div></section>
    <footer className="border-t border-[#dcebed] bg-white px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><Logo href="/" compact/><p className="mt-2 text-xs text-[#819ba1]">My Renewal Quick Overview</p></div><div className="flex flex-wrap gap-5 text-xs font-bold text-[#668087]"><Link href="/login">Sign in</Link><Link href="/signup">Start free</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/settings/support">Feedback</Link></div><p className="text-xs text-[#819ba1]">© {new Date().getFullYear()} MYRQO</p></div></footer>
  </main>;
}

function HeroPreview() { return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -right-5 -top-8 hidden h-32 w-32 rounded-full bg-[#9edbe0]/50 blur-2xl sm:block"/><div className="relative rounded-2xl border border-white bg-white p-4 shadow-[0_25px_60px_rgba(8,47,61,.12)] sm:p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-[10px] font-black uppercase tracking-wider text-[#2d96a4]">MYRQO overview</p><p className="mt-1 text-xl font-black tracking-tight">Good morning</p></div><span className="grid h-9 w-9 place-items-center rounded-full bg-[#eaf6f7] text-[#2d96a4]"><Bell size={16}/></span></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Monthly" value="$152"/><Metric label="Active" value="9"/><Metric label="Next payment" value="$2.99"/></div><div className="mt-4 rounded-xl border border-slate-100 p-4"><div className="flex items-center justify-between"><p className="text-xs font-black">Upcoming renewals</p><span className="text-[10px] font-bold text-[#2d96a4]">View all</span></div><Renewal name="iCloud+" date="in 2 days" amount="$2.99" color="bg-[#398fdb]"/><Renewal name="Netflix" date="in 4 days" amount="$15.49" color="bg-[#e5484d]"/><Renewal name="Spotify" date="in 8 days" amount="$11.99" color="bg-[#21b66f]"/></div></div><div className="absolute -bottom-6 -right-3 hidden rounded-xl border border-[#dcebed] bg-white px-4 py-3 shadow-xl sm:block"><p className="flex items-center gap-2 text-xs font-black text-[#209260]"><Check size={15}/> You&apos;re on top of it</p></div></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f4f8f9] p-3"><p className="text-[9px] font-bold text-[#819ba1]">{label}</p><p className="mt-2 text-sm font-black">{value}</p></div> }
function Renewal({ name, date, amount, color }: { name: string; date: string; amount: string; color: string }) { return <div className="mt-4 flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-lg ${color} text-xs font-black text-white`}>{name[0]}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-black">{name}</span><span className="block truncate text-[10px] text-[#819ba1]">{date}</span></span><strong className="text-xs">{amount}</strong></div> }
function Feature({ icon: Icon, title, text }: { icon: typeof CalendarDays; title: string; text: string }) { return <div><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf6f7] text-[#2d96a4]"><Icon size={18}/></span><h3 className="mt-4 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-[#708b92]">{text}</p></div> }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-xl border border-white/10 bg-white/[.06] p-5"><p className="text-4xl font-black text-[#78c8ce]">{number}</p><h3 className="mt-5 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-[#a9c5ca]">{text}</p></div> }
